### PR TITLE
PXB-3107 (8.0) "--keyring-file-data" does not work with file-based keyring …

### PR DESCRIPTION
**Pull request by patrickbirch**
…component while preparing a backup (8.0)

	modified:   docs/encrypted-innodb-tablespace-backups.md

### CODE REVIEW

**Review by alina-derkach-oaza — APPROVED** [review]
LGTM

**Review by satya-bodapati — CHANGES_REQUESTED** [review]
Lets break the encrypted into multiple sections
1. keyring_file
   a. component vs plugin
2. keyring_aws
   a. component vs plugin
3. keyring_vault
4. keyring_kmip
5. transition key

We should do a real backup and restore test using all these plugin/component types to provide sample configurations and the outputs seen by backups.

We should also fix confirmation messages about the plugin/component detections. Current confirmation messages are about whether the backup is successful or not.

I assume PXB prints something about the keyring plugin or config it uses. If not, please create a bug.

**Comment by satya-bodapati** [comment]
I am suggesting a rewrite of the entire section:face_with_spiral_eyes: sorry

**Comment by satya-bodapati** [comment]
@patrickbirch Thanks for doing the rewrite, Am not able to see the new sections in render link. Can you please check once?

**Comment by satya-bodapati** [comment]
@patrickbirch thanks for breaking and rewriting the entire section. Almost there. I have few more suggestions. I would like to see the topics and contents on the following lines..

```
Encrypted tablespace backup

- Encrypted backups overview

- Encrypted tablespaces backup with keyring_file plugin

   - how to take backup /configuration required. Links to PS documentation on
     server side setup
     
   - asking user to take a backup of these files (required for prepare). Some are
     config files. For the keyring file, file_data (contains keys) should be copied.

   - how to prepare
   
   - copy-back (generate-new-master-key?)
- Encrypted tablespaces backup with keyring_file component
   - how to take backup etc., if no config is needed, all good. We have to tell the user the files
     that PXB would look into
   
   - Are those config files required for prepare? (imagine the user restoring on different
     server)

   - how to prepare 

   - copy-back (generate-new-master-key?)
     
- Encrypted tablespaces backup with keyring KMIP (Key Management..)

  Similar to the above suggestions.
  
- Encrypted tablespaces backup with keyring AWS

- Encrypted tablespaces backup with transition-key

  - Here we have to mention that only prepare will succeed. (I see this is already mentioned somewhere)
     copy-back has to access the keyring and the server startup will need access to the same plugins/vaults anyway
    
 
```

**Pull request closed without merging**
